### ISSUE TITLE
Error with zk new "first": -c: command not found

### ISSUE THREAD

**Issue by francklays** [naps62/zk#2]
Hey @naps62,

I'm new to vim and zettelkasten note taking and your repo is exciting. But I get an error when I try `zk new "first"`:

`/Users/franck/.zk/libexec/zk-new: line 16: -c: command not found`
 
Could you please help ?

**Comment by naps62** [comment]
ah. that's because I'm assuming `EDITOR=vim` (or vi, nvim or other variant)

This is the command you're crashing on:
```
$EDITOR -c ":set autochdir" "$file"
```

You can solve it by adding `export EDITOR=vim` to your bashrc/zshrc (or again, nvim or whatever variant you use)

**Comment by francklays** [comment]
Thanks a lot @naps62, that did it.
